version: '3.8'

services:
  model-training:
    build:
      context: ./modules/
      dockerfile: ./modelling_package/Dockerfile
    environment:
      - BATCH_SIZE
      - EPOCHS
      - ON_GPU
    command: python main.py
    volumes:
      - models_volume:/models
      - data_volume:/data

volumes:
  models_volume:
  data_volume: