# Global options:
[mypy]
warn_return_any = True
warn_unused_configs = True


[mypy-torchvision.*]
ignore_missing_imports = True
follow_untyped_imports = True

# Per-module options:

# [mypy-mycode.foo.*]
# disallow_untyped_defs = True

# [mypy-mycode.bar]
# warn_return_any = False
