[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "modelling"
version = "1.0"
authors = [
  { name="Xavier Dias"},
]
description = "Modelling Package"
requires-python = ">=3.11"
dependencies = [
    "pandas==2.3.3",
    "pydantic==2.12.5",
    "tqdm==4.67.1",
]